---
- name: Download git
  apt: name=git update_cache=yes
  tags:
    - deploy

- name: Install build-essential
  apt: pkg=build-essential state=latest update_cache=yes cache_valid_time=86400
  tags:
    - deploy

- name: Install software-properties-common
  apt: name=software-properties-common update_cache=yes
  tags:
    - deploy

- name: Install python-software-properties
  apt: name=python-software-properties update_cache=yes
  tags:
    - deploy
    
- name: Install python-pip
  apt: name=python-pip update_cache=yes
  tags:
    - deploy
    
- name: Install python2.7-dev
  apt: name=python2.7-dev update_cache=yes
  tags:
    - deploy

- name: Create repository directory
  file: path=/src/my_app state=directory
  tags:
    - deploy

- name: Clone repository
  git: repo={{ openstack_repo }} dest=/src/my_app accept_hostkey=True
  tags:
    - deploy

- name: List
  shell: ls
  async: 45
  poll: 5  
  tags:
    - deploy

- name: List
  shell: cd /src/my_app && ls 
  async: 45
  poll: 5  
  tags:
    - deploy

- name: Pip install requirements
  shell: cd /src/my_app && pip install -rrequirements.txt
  async: 45
  poll: 5  
  tags:
    - deploy

- name: Pip install requirements
  shell: cd /src/my_app && pip install -rtest-requirements.txt
  async: 45
  poll: 5  
  tags:
    - deploy

- name: Install application
  shell: cd /src/my_app && nohup python app.py &
  async: 45
  poll: 5  
  tags:
    - deploy
