---
- name: Download git
  apt: name=git update_cache=yes
  tags:
    - deploy

- name: Clone repository
  git: repo={{ openstack_repo }} dest=/src/my_app accept_hostkey=True
  tags:
    - deploy

- name: Install application
  command: nohup python app.py &
  args:
    chdir: /src/my_app
  tags:
    - deploy
